version: '2'
services:
  web:
    build: .
    command: npm run server
    volumes:
      - .:/app/
    ports:
      - "5555:5555"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache

  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
