version: '2'
services:
  web:
    build: .
    command: nodemon app/server.js -i app/frontend
    volumes:
      - .:/app/
    ports:
      - "5555:5555"
    # depends_on:
    #   - redis
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  # redis:
  #   image: redis:alpine
